name: Release

on:
  push:
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: module-cache
        with:
          path: node_modules
          key: modules-14-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        if: steps.module-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run lint

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: module-cache
        with:
          path: node_modules
          key: modules-14-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.module-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: semantic-release
        run: NPM_TOKEN=$NODE_AUTH_TOKEN npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
